name: Deployments trigger
on:
  deployment
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - if: github.event.deployment == 'deployment'
      run: echo 'Always true'
    - run: echo ${{ github.event.deployment.description }}
