name: Deployments trigger
on:
  deployment
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.sender.login == 'tell-y'
    steps:
    - name: check if ==
      if: github.event.deployment == 'deployment'
      run: echo 'Always true'
    - name: check if !=
      if: github.event.deployment != 'deployment'
      run: echo 'Always false'
    - run: echo ${{ github.event.deployment.ref }}
    - run: echo ${{ github.event.deployment.description }}
    - run: echo ${{ github.event.deployment.task }}
    - run: echo ${{ github.event.deployment.payload }}
    - run: echo ${{ github.event.deployment.environment }}
