name: Deployments trigger
on:
  deployment
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check if ==
      if: github.event.deployment == 'deployment'
      run: echo 'Always true'
    - name: check if !=
      if: github.event.deployment != 'deployment'
      run: echo 'Always false'
    - run: echo '${{ github.event.deployment.description }}'
