name: Play step-if
on:
  push:
    branches:
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'hello 1st'
    - run: echo 'exit 1st' && exit 1
    - run: echo 'this is not run'
    - run: echo 'this is not run' && exit 1
    - name: at if()
      if: ${{ failure() }}
      run: echo 'run this'
