name: Play step-if
on:
  push:
    branches:
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: hello
      id: id_1
      run: echo 'hello 1st' && exit 1
    - name: save status
      if: ${{ always() }}
      run: [ $? != 0 ] && echo ::set-output name=status::failure
    - name: debug
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: hi at if !success()
      id: id_2
      if: ${{ !success() }}
      run: echo 'hi'
    - name: (cancelled)
      id: id_3
      run: echo 'this is not run' || echo ::set-output name=status::failure
    - name: at if() !success() && !cancelled()
      id: id_4
      if: ${{ !success() && !cancelled() }}
      run: echo 'hi'
    - name: (cancelled)
      run: echo 'this is not run' && exit 1
      id: id_5
    - name: at if() failure()
      id: id_6
      if: ${{ failure() }}
      run: echo 'hi'
    - name: (cancelled)
      run: echo 'this is not run'
      id: id_7
    - name: at if() check id_1
      id: id_8
      if: ${{ failure() && steps.id_1.outputs.status == 'failure' }}
      run: echo 'this is run'
    - name: at if() check id_5
      id: id_9
      if: ${{ failure() && steps.id_5.outputs.status == 'failure' }}
      run: echo 'this is not run'
