name: Play step-if
on:
  push:
    branches:
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: hello
      id: id_is_hello
      run: echo 'hello 1st' && exit 1
    - run: echo 'this is not run'
    - run: echo 'this is not run' && exit 1
    - name: at if()
      if: ${{ failure() && contains(toJson(steps), 'id_is_hello') }}
      run: echo 'hi'
    - name: echo 'running'
      id: running
    - name: at if() (not running)
      if: ${{ failure() && contains(toJson(steps), 'running') }}
      run: echo 'this is not run'
